name: teknotes
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  http: ^1.1.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
#    - assets/images/wifi-signal-light.png
#    - assets/images/logofinalfile-01-removebg-preview-1-pZ3.png
#    - assets/images/documents-svgrepo-com-1.png
#    - assets/images/battery-light.png
#    - assets/images/bell.png
#    - assets/images/bxs-home.png
#    - assets/images/vector-Cxm.png
#    - assets/images/time-light-yKj.png
#    - assets/images/settings-svgrepo-com-1.png
#    - assets/images/battery-light-Ppy.png
#    - assets/images/network-signal-light-oVF.png
#    - assets/images/rectangle-24.png
#    - assets/images/image-2.png
#    - assets/images/image-removebg-preview-8-1.png
#    - assets/images/wifi-signal-light-HdP.png
#    - assets/images/frame-56308.png
#    - assets/images/top-meun.png
#    - assets/images/image-3.png
#    - assets/images/documents-svgrepo-com-1-imK.png
#    - assets/images/time-light-tHT.png
#    - assets/images/funnelsimple.png
#    - assets/images/vector-H2d.png
#    - assets/images/frame-56308-nP7.png
#    - assets/images/network-signal-light-Jv1.png
#    - assets/images/list-vku.png
#    - assets/images/frame-56308-PWu.png
#    - assets/images/vector-wmf.png
#    - assets/images/vector-BAm.png
#    - assets/images/vector-eTX.png
#    - assets/images/vector-KNd.png
#    - assets/images/wifi-signal-light-UAh.png
#    - assets/images/battery-light-dgR.png
#    - assets/images/arrowsquareleft.png
#    - assets/images/ellipse-1-bg.png
#    - assets/images/frame-56305.png
#    - assets/images/ellipse-3-bg.png
#    - assets/images/bxs-home-g4d.png
#    - assets/images/component-3-Bjs.png
#    - assets/images/ellipse-1-bg-NdT.png
#    - assets/images/vector-HxH.png
#    - assets/images/ellipse-3-bg-qed.png
#    - assets/images/frame-56308-gM3.png
#    - assets/images/frame-56308-MRo.png
#    - assets/images/vector-FCy.png
#    - assets/images/settings-svgrepo-com-1-rYD.png
#    - assets/images/ellipse-3-bg-FRF.png
#    - assets/images/ellipse-2-bg.png
#    - assets/images/ellipse-3-bg-Mm7.png
#    - assets/images/ellipse-2-bg-tPF.png
#    - assets/images/ellipse-2-bg-vHB.png
#    - assets/images/ellipse-1-bg-WDs.png
#    - assets/images/ellipse-1-bg-6oP.png
#    - assets/images/ellipse-1-bg-oQq.png
#    - assets/images/ellipse-3-bg-uTj.png
#    - assets/images/battery-light-Lbf.png
#    - assets/images/vector-Lay.png
#    - assets/images/vector-uDw.png
#    - assets/images/ellipse-2-bg-ZBj.png
#    - assets/images/vector-Bjj.png
#    - assets/images/ellipse-2-bg-ZrM.png
#    - assets/images/vector-8qT.png
#    - assets/images/vector-Seq.png
#    - assets/images/wifi-signal-light-w2D.png
#    - assets/images/vector-G6R.png
#    - assets/images/documents-svgrepo-com-1-tCV.png
#    - assets/images/vector-b6D.png
#    - assets/images/vector-1XB.png
#    - assets/images/vector-NwP.png
#    - assets/images/top-meun-aA1.png
#    - assets/images/vector-A45.png
#    - assets/images/vector-5XK.png
#    - assets/images/vector-jQh.png
#    - assets/images/vector-nrh.png
#    - assets/images/vector-EBo.png
#    - assets/images/network-signal-light-6jo.png
#    - assets/images/arrowsquareleft-TH7.png
#    - assets/images/list-gZs.png
#    - assets/images/vector-bkZ.png
#    - assets/images/funnelsimple-JAh.png
#    - assets/images/vector-hfB.png
#    - assets/images/time-light-yPb.png
#    - assets/images/vector-6Nh.png
#    - assets/images/frame-56305-7rM.png
#    - assets/images/vector-8PF.png
#    - assets/images/vector-sKT.png
#    - assets/images/vector-jJV.png
#    - assets/images/vector-5jK.png
#    - assets/images/bxs-home-FTb.png
#    - assets/images/rectangle-669.png
#    - assets/images/settings-svgrepo-com-1-ie9.png
#    - assets/images/vector-r9B.png
#    - assets/images/vector-Kho.png
#    - assets/images/component-3.png
#    - assets/images/component-3-nxV.png
#    - assets/images/vector-EVB.png
#    - assets/images/component-3-PHw.png
#    - assets/images/component-3-fzm.png
#    - assets/images/component-3-GaR.png
#    - assets/images/component-3-Yn1.png
#    - assets/images/component-3-uZo.png
#    - assets/images/component-3-E8V.png
#    - assets/images/component-3-Mn5.png
#    - assets/images/component-3-Wgm.png
#    - assets/images/component-3-6vR.png
#    - assets/images/component-3-kBo.png
#    - assets/images/vector-iXw.png
#    - assets/images/component-3-9Wm.png
#    - assets/images/vector-WPF.png
#    - assets/images/component-3-st1.png
#    - assets/images/component-3-Pu7.png
#    - assets/images/component-3-BHf.png
#    - assets/images/vector-wY1.png
#    - assets/images/component-3-Xmw.png
#    - assets/images/vector-f3K.png
#    - assets/images/funnelsimple-T1F.png
#    - assets/images/vector-gRj.png
#    - assets/images/component-3-Lqb.png
#    - assets/images/vector-uhX.png
#    - assets/images/vector-QkV.png
#    - assets/images/vector-sWD.png
#    - assets/images/wifi-signal-light-KAD.png
#    - assets/images/wifi-signal-light-PMf.png
#    - assets/images/time-light-gLm.png
#    - assets/images/battery-light-ruT.png
#    - assets/images/search.png
#    - assets/images/frame-56305-h1o.png
#    - assets/images/network-signal-light-nL5.png
#    - assets/images/list-rhB.png
#    - assets/images/time-light-5sB.png
#    - assets/images/network-signal-light-Kp1.png
#    - assets/images/component-3-Uzy.png
#    - assets/images/arrowsquareleft-jNd.png
#    - assets/images/list-ubs.png
#    - assets/images/list-t8d.png
#    - assets/images/component-3-s8y.png
#    - assets/images/wifi-signal-light-yYZ.png
#    - assets/images/arrowsquareleft-Jqj.png
#    - assets/images/list-zhs.png
#    - assets/images/user.png
#    - assets/images/list-6sf.png
#    - assets/images/list-arR.png
#    - assets/images/battery-light-a5B.png
#    - assets/images/top-meun-Mj3.png
#    - assets/images/list-6Rj.png
#    - assets/images/copy.png
#    - assets/images/network-signal-light-PWD.png
#    - assets/images/battery-light-uB3.png
#    - assets/images/component-3-Gih.png
#    - assets/images/component-3-q5F.png
#    - assets/images/time-light-iVj.png
#    - assets/images/vector-Tjs.png
#    - assets/images/battery-light-Rzu.png
#    - assets/images/list-Shb.png
#    - assets/images/frame-11253.png
#    - assets/images/network-signal-light-ycR.png
#    - assets/images/frame-56305-zEZ.png
#    - assets/images/arrowsquareleft-AYV.png
#    - assets/images/wifi-signal-light-X9P.png
#    - assets/images/time-light-Hc9.png
#    - assets/images/time-light-46y.png
#    - assets/images/time-light-517.png
#    - assets/images/vector-TU9.png
#    - assets/images/network-signal-light-UJR.png
#    - assets/images/vector-uky.png
#    - assets/images/wifi-signal-light-Y8u.png
#    - assets/images/vector-aE1.png
#    - assets/images/battery-light-mX3.png
#    - assets/images/vector-c3o.png
#    - assets/images/frame-56305-GbP.png
#    - assets/images/battery-light-i9j.png
#    - assets/images/wifi-signal-light-sNd.png
#    - assets/images/network-signal-light-ZMf.png
#    - assets/images/arrowsquareleft-mMf.png
#    - assets/images/network-signal-light-bDX.png
#    - assets/images/time-light-s65.png
#    - assets/images/vector-18Z.png
#    - assets/images/vector-Brd.png
#    - assets/images/vector-mTK.png
#    - assets/images/arrowsquareleft-rmT.png
#    - assets/images/vector-edK.png
#    - assets/images/vector-uSm.png
#    - assets/images/vector-byo.png
#    - assets/images/vector-FMP.png
#    - assets/images/import-content-svgrepo-com-1.png
#    - assets/images/time-light-4KP.png
#    - assets/images/vector-qss.png
#    - assets/images/battery-light-Qjw.png
#    - assets/images/vector-Bbb.png
#    - assets/images/wifi-signal-light-CMb.png
#    - assets/images/vector-wNm.png
#    - assets/images/battery-light-SZb.png
#    - assets/images/vector-t6y.png
#    - assets/images/frame-11253-MHP.png
#    - assets/images/frame-11253-nKP.png
#    - assets/images/page-1.png
#    - assets/images/arrowsquareleft-Guj.png
#    - assets/images/vector-wBs.png
#    - assets/images/vector-7hw.png
#    - assets/images/vector-gv9.png
#    - assets/images/wifi-signal-light-oyX.png
#    - assets/images/vector-kER.png
#    - assets/images/arrowsquareleft-jPB.png
#    - assets/images/vector-W2Z.png
#    - assets/images/vector-m8q.png
#    - assets/images/network-signal-light-MAu.png
#    - assets/images/vector-t4M.png
#    - assets/images/vector-Z7K.png
#    - assets/images/vector-cPf.png
#    - assets/images/vector-aNh.png
#    - assets/images/frame-56304.png
#    - assets/images/vector-Aey.png
#    - assets/images/time-light-hGq.png
#    - assets/images/wifi-signal-light-YE9.png
#    - assets/images/vector-eHs.png
#    - assets/images/battery-light-PW5.png
#    - assets/images/pen-1320-svgrepo-com-1.png
#    - assets/images/property-1default.png
#    - assets/images/property-1default-9ND.png
#    - assets/images/wifi-signal-light-nwX.png
#    - assets/images/property-1variant2.png
#    - assets/images/vector-Bx9.png
#    - assets/images/battery-light-mg1.png
#    - assets/images/vector-W1s.png
#    - assets/images/vector-Fu7.png
#    - assets/images/icon-eye.png
#    - assets/images/network-signal-light-Uiq.png
#    - assets/images/facebook.png
#    - assets/images/auto-group-xe3w.png
#    - assets/images/image-4.png
#    - assets/images/vector-Mv5.png
#    - assets/images/battery-light-Ted.png
#    - assets/images/time-light-jWd.png
#    - assets/images/time-light-MK3.png
#    - assets/images/network-signal-light-nn1.png
#    - assets/images/vector-xnq.png
#    - assets/images/icon-eye-v5s.png
#    - assets/images/network-signal-light-Gk5.png
#    - assets/images/network-signal-light-XkH.png
#    - assets/images/battery-light-Yyj.png
#    - assets/images/apple_store.png
#    - assets/images/property-1variant2-Mxy.png
#    - assets/images/xsquare.png
#    - assets/images/time-light-fCy.png
#    - assets/images/wifi-signal-light-rWH.png
#    - assets/images/xsquare-QGu.png
#    - assets/images/logofinalfile-01-removebg-preview-1-HG9.png
#    - assets/images/google.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
